
spring.application.name=QuizLand

spring.datasource.url=jdbc:postgresql://dpg-d38qomhr0fns738777k0-a.frankfurt-postgres.render.com\
  :5432/quizland_database?user=quizland_database_user&password=zHGLkLjeVBU4ejROh2cexGU3leJx3cnP&sslmode=require


spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=create

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: show SQL statements in logs (for debugging)
spring.jpa.show-sql=true
